back/package-lock.json, back/package.json, back/src/auth/auth.controller.ts, back/src/main.ts, docker-compose.yml
=> feat: back .env configuration

back/src/auth/auth.controller.ts, back/src/auth/auth.service.ts, back/src/main.ts
=> feat: #15 auth basic code constructor

front/package-lock.json, front/src/App.js, front/src/Components/AllProjectPage/AllProjectPage.js, front/src/Components/AllProjectPage/ProjectContents.js, front/src/Components/AllProjectPage/ProjectTypeBar.js, front/src/SCSS/AllProjectPage/ProjectGrid.scss, front/src/SCSS/AllProjectPage/ProjectTypeBar.scss
- AllProjectPage에 대한 레이아웃 생성.
- Cards 컴포넌트를 활용하여 그리드로 구성.
- App.js에 AllProjectPage로 연결하기위해 라우터 생성.
=> feat: #19 add AllProjectPage layout

front/src/Components/AllProjectPage/AllProjectPage.js, front/src/Components/CommonComponent/Navbar.js, front/src/SCSS/AllProjectPage/AllProjectPage.scss, front/src/SCSS/AllProjectPage/ProjectGrid.scss
- 화면이 커질 때, 카드의 padding도 같이 늘어나는 현상을 수정하였습니다.
- mainpage 에서 프로젝트를 클릭할 때, AllProjectPage로 이동되도록 routing하였습니다.
=>  feat: #24 Cards margin-right modify + Router

front/src/SCSS/Navbar.scss
notification 맨 마지막 Card가 튀어나오는 현상을 수정하였습니다.
=>  style: #26 notification style mod

back/Dockerfile, back/config/config.json, back/models/index.js, back/models/test.js, back/package-lock.json, back/package.json, back/src/main.ts, docker-compose.yml
- docker-compose.yml 파일에 db 서비스를 추가하였습니다.
- db 디렉토리 .env 파일에 MySQL 계정 정보와 db 정보를 입력하였습니다. 아래는 .env 파일 템플릿 입니다.
```
MYSQL_HOST=db
MYSQL_PORT=3306
MYSQL_ROOT_PASSWORD='root 계정 비밀번호'
MYSQL_DATABASE='생성할 database'
MYSQL_USER='user name'
MYSQL_PASSWORD='user password'
```
- Sequelize 설치 후, `sequelize init` 명령어 입력 시 생성되는 파일 `config/config.json`, `models/index.js`를 추가하였습니다.
- `config.json`파일의 development property에 mysql container에서 생성된 mysql 계정과 database를 입력하면 됩니다. (보안 상의 이유로 다음 커밋 때부터 계정 정보와 database를 null로 입력하여 커밋할 예정)
- models 디렉토리에 `test.js` 파일을 추가하여 테스트 목적으로 user 테이블을 생성합니다.
- `npm start` 명령어 입력 시 실행되는 `main.ts` 파일에 sequelize로 db와 연결하는 구문을 추가하였습니다.
++ `/back/Dockerfile` 수정하였습니다.
`main.ts` require 문법에서 import 문법으로 수정하였습니다.
=> feat: #12 #23 add MySQL container and install Sequelize

back/package-lock.json, back/package.json, back/src/main.ts, back/src/routes/auth/oauth.ts
=> feat: #42 blacklist token collector

front/package-lock.json, front/package.json, front/src/Components/AllProjectPage/AllProjectPage.js, front/src/Components/AllProjectPage/ProjectPaginate.js, front/src/SCSS/AllProjectPage/ProjectGrid.scss, front/src/SCSS/AllProjectPage/ProjectPaginate.scss, front/src/SCSS/AllProjectPage/ProjectTypeBar.scss
- 프로젝트 페이지 리스트 전환을 위한 페이지네이션을 추가함.
- react-js-pagination 패키지를 활용함.
- 아직 누를때, 프로젝트 리스트가 바뀌는 것을 적용하지 않음.
- 데이터가 있다고 가정하고 적용할 예정.
=> feat : #19 add pagination to allprojectpage

back/src/interface/profile.interface.ts, back/src/models/user/blacklist.model.ts, back/src/models/user/follow.model.ts, back/src/models/user/otoken.model.ts, back/src/models/user/profile.model.ts, back/src/models/user/token.model.ts, back/src/models/user/user.model.ts, back/src/module/time.ts, back/src/routes/auth/auth.service.ts, back/src/routes/index.ts, back/src/routes/user/user.controller.ts, back/src/routes/user/user.service.ts, back/tsconfig.json
=> feat: #48 profile page

back/package-lock.json, back/package.json, back/src/main.ts
=> feat: #50 cross origin resource sharing

back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
- url : `http://localhost:5000/project`
- request (query)
1. state : string, 프로젝트의 상태(`recruiting`, `proceeding`, `completed`)
2. page : number, 페이지
3. pageSize : number, 페이지당 카드 갯수
4. tag : string[], 기술스택을 가리키는 tag
- tag 테이블과 projecttag 테이블도 역시 project 테이블과 마찬가지로 임의의 데이터를 직접 넣어주셔야 합니다.
(https://velog.io/@du0928/42DoProject-개발일지 링크에 작성되어 있는 sql을 복붙하시면 쉽게 데이터 입력 가능)
- 요청은 querystring으로 보내주시면 됩니다.
(Ex : `http://localhost:5000/project?state=completed&page=1&pageSize=3&tag=react&tag=express`)
- post 기능이 추가되기 전까진 db 컨테이너에서 임의로 `projects` 테이블에 값을 넣으신 후, 테스트해주시면 됩니다.
(Ex : `INSERT INTO projects (title, totalMember, currentMember, state, like, createdAt, updatedAt) VALUE('42DoProject', 5, 5, 'proceeding', 200, NOW(), NOW());`)
- url : `http://localhost:5000/project`
- request (body)
1. title : …
=> feat: #73 #78 add project list to table and delete project list

back/src/models/index.ts, back/src/routes/project/project.service.ts
- tag 모델이 null이 아닐 때에는 초기화하는 로직을 거치치않게 코드를 수정하였습니다.
=> [back] feat: #105 fix tag init error

back/src/routes/project/project.service.ts
- 필요한 정보만 전송할 수 있게끔 attribution 옵션을 추가하였습니다.
- 코드의 안정성을 위해 변수 타입을 변경하였습니다.
=> feat: #113 project API code refactoring

back/src/models/user/user.model.ts, back/src/routes/auth/auth.service.ts
#64 #86 이슈 처리했습니다.
#86 수정 내용은 notion API 명세 auth/ 페이지에 있습니다
=> feat: #64 #86 issue

back/src/routes/project/project.service.ts
=> [back] feat: #120 project router code refactoring

back/src/models/project/content.model.ts, back/src/routes/project/project.service.ts
- project content의 조회수 기능을 추가하였습니다.
- content table의 viewCount column을 통해 접근 가능합니다. (자세한건 notion project API 명세에 업데이트 하겠습니다.)
=> [back] feat: #137 add cal view count

front/src/Components/CommonComponent/Chat.js, front/src/Components/CommonComponent/Navbar.js, front/src/Components/MainPage/Dashboard.js, front/src/Components/MainPage/PopUp.js, front/src/Components/ProfileEditPage/ProfileEditBody.js, front/src/Components/ProfilePage/Follow.js, front/src/Components/ProfilePage/ProfileBody.js, front/src/Components/ProfilePage/ProfileHeader.js, front/src/SCSS/ProfilePage/Follow.scss, front/src/SCSS/ProfilePage/ProfileBody.scss, front/src/SCSS/ProfilePage/ProfileHeader.scss, front/src/skills.json
스킬 태그들을 
(lanugages / frameworks / servers / databases / mldl /gaming) 분류로 나누어 이름과 이미지를 저장했습니다.
각 분류별로
```
{
"0": [
"Godot Engine",
"https://img.shields.io/badge/GODOT-%23FFFFFF.svg?style=flat-square&logo=godot-engine"
]
}
```
와 같은 형태입니다.
=> feat: #134 add skills.json

back/src/models/user/profile.model.ts, back/src/routes/auth/auth.service.ts
=> feat: #164 level to intra level

back/src/models/user/profile.model.ts, back/src/models/user/user.model.ts, back/src/routes/user/user.service.ts
=> feat: user introduction, statusMessage limit

back/src/routes/user/user.service.ts
=> feat: json parse string to number

back/src/routes/user/user.controller.ts, back/src/routes/user/user.service.ts, back/src/socket/index.ts
동접자 확인 부분입니다.
`/user` 페이지에 업데이트 하겠습니다
=> feat: #69 realtime concurrent users

back/src/models/project/project.model.ts, back/src/routes/project/project.service.ts
- position tag에 따른 filtering 기능을 추가했습니다.
- unsplash API image 링크를 저장할 column을 추가했습니다.
- project의 총 갯수를 get할 수 있습니다.
=> feat: #136 #184 modify tag filtering and get total number of project

back/src/routes/user/user.service.ts
=> feat: #190 introduction, statusMessage

back/src/models/project/applyprojectprofile.model.ts, back/src/models/project/likeprojectprofile.model.ts, back/src/models/project/project.model.ts, back/src/models/user/profile.model.ts, back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
- get project list 부분 code 리팩토링 하였습니다.
- get content API를 통해 project에 참여중인 user의 profile image를 받아볼 수 있게 수정하였습니다.
- 프로젝트 신청(applyTeam) API를 추가하였습니다.
- 프로젝트 신청 현황을 확인(getApplyerList) API를 추가하였습니다.
- 프로젝트 신청을 취소하거나 거절(cancelApply) API를 추가하였습니다.
- 프로젝트 신청을 수락하여 팀 멤버에 추가(addMember)하는 API를 추가하였습니다.
- 프로젝트 팀 멤버를 퇴장(deleteMember)시키는 API를 추가하였습니다.
- 자세한 설명은 merge 후 project API 명세에 추가하겠습니다.
=> feat: #186 #187 get user profile image and join team

back/src/interface/user.interface.ts, back/src/main.ts, back/src/models/user/feed.mongo.ts, back/src/models/user/profile.model.ts, back/src/routes/auth/auth.service.ts, back/src/routes/index.ts, back/src/routes/user/user.service.ts, back/src/socket/index.ts
feed 가져오는 부분과 last access 부분을 수정했습니다.
현재 접속 중 (로그인)이라면 last access가 시간이 아닌 online을 나타냅니다.
=> [back] feed, last access

back/src/routes/index.ts, back/src/routes/user/user.controller.ts
=> feat: guest can access following, follower list

back/src/routes/auth/auth.service.ts, back/src/routes/index.ts
최초 가입 유저에게 "프로젝트를 찾는 중" 상태를 할당합니다.
=> [back] feat: #344 give 1 status to signed up user

front/src/Components/AllProjectPage/ProjectTypeBar.js, front/src/Components/LoungePage/LoungeBody.js, front/src/Components/MainPage/CadetCards.js, front/src/Components/MainPage/Dashboard.js, front/src/Components/MainPage/PopUp.js, front/src/Components/ProfileEditPage/ProfileEditBody.js, front/src/Components/ProfileEditPage/ProfileEditHeader.js, front/src/Components/ProfileEditPage/ProfileEditPage.js, front/src/Components/ProfilePage/Follow.js, front/src/Components/ProfilePage/ProfileBody.js, front/src/Components/ProfilePage/ProfileHeader.js, front/src/Components/ProfilePage/ProfilePage.js, front/src/Components/ProfilePage/UnfollowAlert.js, front/src/Components/ProjectEditPage/ProjectEditPage.js, front/src/Components/ProjectEditPage/Unsplash.js, front/src/SCSS/AllProjectPage/ProjectTypeBar.scss, front/src/SCSS/MainPage/CadetCards.scss, front/src/SCSS/ProfilePage/ProfileBody.scss, front/src/SCSS/ProfilePage/ProfileHeader.scss
- 로그인 하지 않고 프로젝트 생성 버튼 클릭 시 모달 창이 뜨고, 로그인 해야만 프로젝트 생성 페이지에 진입할 수 있도록 하였습니다.
- 프로젝트 이미지 선택 시 jpg 확장자를 추가하였습니다.
(맥에서 테스트할 경우 jpg 파일도 jpeg에 포함이 되어 확인이 어려운 것 같습니다. 윈도우 환경에서 테스트가 필요합니다.)
- 대쉬보드의 "진행 중인 프로젝트"의 의미가 불분명한 문제가 있어 "참여중인 프로젝트"로 변경하였습니다.
- 팔로우 창에서 팔로우시 accessToken을 정상적으로 가져올 수 있도록 수정했습니다.
=> feat: #347 front bug fix

back/src/module/aws/s3.ts, back/src/routes/auth/auth.service.ts, back/src/routes/index.ts
profile 이미지가 올라간 이후에 처리를 진행합니다
=> [back] feat: #346 profile image

back/src/module/search.ts, back/src/routes/search/search.service.ts
=> [back] feat: #350 all user pagination

back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
- project 필터링이 잘 안되서 오류 수정했습니다.
- 1차적으로 refactoring 했습니다.
=> feat: #222 project API code refactoring

.github/workflows/frontend.yml
=> [deploy] 프론트 배포 테스트

back/src/interface/search.interface.ts, back/src/module/cadetqueue.ts, back/src/module/search.ts, back/src/routes/auth/auth.service.ts, back/src/routes/index.ts, back/src/routes/search/search.service.ts, back/src/routes/user/user.service.ts
로그인 하지 않았을 경우 보이는 프로필 이미지를 블러처리합니다
=> feat: #380 send blur image to unauthorized user

front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/Components/ProjectDetail/WaitList.js, front/src/SCSS/ProjectDetail/MemberList.scss, front/src/SCSS/ProjectDetail/WaitList.scss
- 프로필 상세페이지에 신청리스트 버튼 구현
- 멤버 프로필을 클릭하면 프로필페이지로 이동 가능
=> feat : #385 add waitlist button

back/src/models/lounge/likelounge.model.ts, back/src/models/lounge/likereply.model.ts, back/src/models/lounge/lounge.model.ts, back/src/models/lounge/replyoflounge.model.ts, back/src/models/user/profile.model.ts, back/src/module/feed.ts, back/src/routes/index.ts, back/src/routes/lounge/lounge.controller.ts, back/src/routes/lounge/lounge.service.ts, back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts, back/src/routes/user/user.service.ts
1. lounge CRUD API
2. replyOfLounge CRUD API (답글 작성 시, 해당 라운지 작성자에게 피드알림 전송)
3. like lounge and like reply API
1. changeProjectLeader API
=> feat: #384 #392 #394 Lounge changeLeader reverseOrder

back/src/routes/user/user.service.ts
=> feat: #396 fix unfollow bug

front/src/Components/CommonComponent/Chat/Chat.js, front/src/Components/CommonComponent/Chat/InChat.js, front/src/SCSS/Common/Chat/Chat.scss, front/src/SCSS/Common/Chat/InChat.scss, front/src/SCSS/Common/Navbar/Navbar.scss, front/src/redux/reducer/LoginReducer.js
채팅 이전 기록 가져오는 기능 추가
로그아웃 시 소켓 로그아웃
=> feat: #401 Add before Chat log, socket Logout

back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
=> fix: #406 fix error about position correction

front/src/Components/CadetPage/AllCadet.js, front/src/Components/CadetPage/RecruitCadet.js, front/src/Components/CommonComponent/Navbar/SearchCard.js, front/src/Components/MainPage/Cadet.js, front/src/Components/ProfilePage/ProfilePage.js
- 로그인 시 블러되지 않은 이미지를 표시할 수 있게 요청에 accessToken 을 추가하였습니다.
=> feat: #399 add accessToken to get profile images

front/src/App.js, front/src/Components/CommonComponent/Chat/ChatCard.js, front/src/Components/CommonComponent/Chat/INChatConv.js, front/src/Components/CommonComponent/Chat/InChat.js, front/src/Components/CommonComponent/Chat/UserNameCard.js, front/src/Components/CommonComponent/Navbar/ProjectCard.js, front/src/Components/CommonComponent/Navbar/SearchCard.js, front/src/Components/MainPage/PublicList.js, front/src/Components/MainPage/RecruitList.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/SCSS/Common/Chat/InChat.scss
Image Resize
- 채팅 카드(O)
- 채팅 유저 초대 선택 이미지(O)
- 메인페이지 검색(O)
- 메인 페이지 검색 결과 이동 Router수정(O)
- 메인 페이지 프로젝트 고유 Key수정(O)
=> [DEPLOY] Image Resize 

back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
- 프로젝트의 상태만 변경하는 API를 추가했습니다.
- postList API의 응답으로 projectId 값을 추가했습니다.
=> feat: #451 #455 add modifying state API and fix response of postList API

back/src/routes/index.ts
=> [back] feat: feed dump

back/src/interface/user.interface.ts, back/src/models/user/feed.mongo.ts, back/src/module/feed.ts
- mongo에 project feed 알림 정보가 저장안되는 오류를 수정했습니다.
=> fix: #481 fix project feed error

back/src/routes/project/project.service.ts
- skill과 position 요청이 배열로 들어왔을 때 발생하는 에러를 해결하였습니다.
=> fix: #452 fix project filtering error

back/src/routes/lounge/lounge.service.ts, back/src/routes/project/project.service.ts
- 프로젝트 수정페이지에서 포지션 삭제 시 totalMember가 잘못계산되는 오류를 수정했습니다.
- getLounve API 오류를 수정했습니다.
=> fix: #507 fix totalMember error in updateList API and getLounge error

back/src/routes/lounge/lounge.service.ts
- access token 유무에 따라 profileImage or blurImage를 보내주는 로직을 추가하였습니다.
=> feat: #524 add blur image response in getLounge API

back/src/module/aws/s3.ts, back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
=> [back] feat: #528 project content image

back/src/routes/lounge/lounge.controller.ts, back/src/routes/lounge/lounge.service.ts
- getLounge API의 응답에 loungeId를 추가하였습니다.
- 라운지마다 좋아요의 유무를 받아볼 수 있습니다.
=> feat: #530 #531 add loungeId to getLounge API response and checking like

back/src/routes/lounge/lounge.service.ts
=> fix: #546 add userId to response of getLounge API

front/src/Components/AllProjectPage/CompleteProjects.js, front/src/Components/AllProjectPage/Filter.js, front/src/Components/AllProjectPage/ProceedProjects.js, front/src/Components/AllProjectPage/ProjectPaginate.js, front/src/Components/AllProjectPage/ProjectTypeBar.js, front/src/Components/AllProjectPage/RecruitProjects.js, front/src/Components/ProjectDetail/CheckModal.js, front/src/Components/ProjectDetail/MemberCard.js, front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectComment.js, front/src/Components/ProjectDetail/ProjectContent.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/Components/ProjectDetail/ProjectInfo.js, front/src/Components/ProjectDetail/ProjectStatusChange.js, front/src/Components/ProjectDetail/WaitList.js, front/src/SCSS/AllProjectPage/Filter.scss, front/src/SCSS/ProjectDetail/CheckModal.scss, front/src/SCSS/ProjectDetail/MemberList.scss, front/src/SCSS/ProjectDetail/ProjectContent.scss, front/src/SCSS/ProjectDetail/ProjectStatusChange.scss, front/src/SCSS/ProjectDetail/WaitList.scss
- 프로젝트 리스트 필터기능 구현함
- 댓글 수정기능 추가구현
- 프로젝트 상태변경 기능 구현
- css 수정 필요
=> feat : add project list filter

front/src/Components/AllProjectPage/Filter.js, front/src/Components/LoungePage/LoungeWrite.js, front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectComment.js, front/src/Components/ProjectDetail/ProjectContent.js, front/src/Components/ProjectDetail/ProjectInfo.js, front/src/SCSS/AllProjectPage/Filter.scss, front/src/SCSS/LoungePage/LoungePost.scss, front/src/SCSS/LoungePage/LoungeWrite.scss, front/src/SCSS/ProjectDetail/CheckModal.scss, front/src/SCSS/ProjectDetail/MemberList.scss, front/src/SCSS/ProjectDetail/ProjectComment.scss, front/src/SCSS/ProjectDetail/ProjectContent.scss, front/src/SCSS/ProjectDetail/ProjectDetail.scss, front/src/SCSS/ProjectDetail/ProjectDetailHeader.scss, front/src/SCSS/ProjectDetail/ProjectStatusChange.scss
- 프로젝트의 리더에게는 "나가기" 버튼이 보이지 않게 수정했습니다.
=> fix: #432 fix leader out

back/src/module/cadetqueue.ts, back/src/routes/auth/auth.service.ts, back/src/routes/index.ts
가입 시 상태를 0으로 설정하고, 메인에 뜨지 않게 합니다
=> [back] feat: #573 set status

front/src/Components/ProjectDetail/MemberCard.js, front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectComment.js, front/src/Components/ProjectDetail/ProjectContent.js, front/src/Components/ProjectDetail/ProjectInfo.js, front/src/Components/ProjectDetail/ProjectStatusChange.js, front/src/SCSS/ProjectDetail/MemberList.scss
- 멤버리스트 wrap잘못되는 버그 수정.
- 참고주소 favicon 버그 수정.
- 댓글 수정창 안닫아지는 버그 수정.
- 댓글 삭제 or 추가할떄 페이지변경안되는 버그 수정.
=> fix : #581 fixed bugs in project detail page.

front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/Components/ProjectDetail/WaitList.js
- 신청리스트 카운트가 바로 반영안되는 버그 수정.
- 알림으로 멤버가 된 프로젝트에가면 랜더링이 일부 안되는 버그 수정.
=> fix : #584 waitlist count bug fix

front/src/Components/ProjectDetail/ProjectComment.js, front/src/SCSS/ProjectDetail/ProjectComment.scss
=> feat : add comment time info

front/src/Components/CommonComponent/Footer.js, front/src/Components/CommonComponent/Navbar/NotiCard.js, front/src/Components/LoungePage/CommentElement.js, front/src/Components/LoungePage/LoungeComment.js, front/src/Components/LoungePage/LoungePost.js, front/src/Components/ProjectDetail/MemberCard.js, front/src/Components/ProjectDetail/MemberList.js, front/src/SCSS/LoungePage/LoungeComment.scss, front/src/SCSS/LoungePage/LoungePost.scss, front/src/SCSS/ProfilePage/ProfileHeader.scss
- 라운지 댓글 수정 및 삭제, 프로필 이동
- 프로젝트 상세페이지 memberlist 부트스트랩 툴팁 위치 이동(memberlist 요소 전체 -> memberlist 이미지)
=> feat: #567 add comment edit/delete

back/src/routes/lounge/lounge.service.ts, back/src/routes/project/project.service.ts
- 라운지 답글 순서를 reverse 하였습니다.
- 라운지 답글 삭제 오류를 수정하였습니다.
- 팀원일 때 팀 나가기 오류를 수정하였습니다.
=> fix: #591 #604 fix delete member error and change ordering lounge reply

back/src/routes/project/project.service.ts
- 프로젝트의 상태가 바뀔 때 피드알림이 팀원들에게 전송되지 않는 오류를 수정하였습니다.
=> fix: #590 fix feed notification error

front/src/Components/LoungePage/LoungeComment.js, front/src/Components/ProjectDetail/MemberCard.js, front/src/Components/ProjectEditPage/Modal.js, front/src/Components/ProjectEditPage/ProjectEditPage.js, front/src/Components/ProjectEditPage/Unsplash.js, front/src/SCSS/Common/Navbar/Navbar.scss, front/src/SCSS/MainPage/Lounge.scss
- 범용성을 위해 modal.js 컴포넌트를 변경하였습니다.
1. 기존의 "취소", "확인" 이외에도 다양한 button 내용을 props로 전달할 수 있습니다.
2. setYes, setOpenFlag 등을 없애고 직관적인 confirmFunc, cancelFunc으로 변경하였습니다.
- 이외에 project memberlist 쪽 부트스트랩 툴팁을 수정하였습니다.
=> feat: #626 modify modal.js

back/src/routes/project/project.service.ts
=> fix: #652 fix error feed notification

front/src/Components/AllProjectPage/ProjectFilter.js, front/src/Components/AllProjectPage/ProjectTypeBar.js, front/src/Components/CadetPage/AllCadet.js, front/src/Components/CadetPage/CadetFilter.js, front/src/Components/CadetPage/CadetTypeBar.js, front/src/Components/CadetPage/RecruitCadet.js, front/src/SCSS/AllProjectPage/ProjectFilter.scss, front/src/SCSS/CadetPage/CadetFilter.scss, front/src/SCSS/CadetPage/CadetTypeBar.scss
- 카뎃리스트의 필터 구현.
- 프로젝트 필터, 카뎃 필터가 이전에 입력한 데이터 갖고 있도록 설정.
- 외부 클릭시 꺼지게 만들었음.
=> feat : #621 add cadet list filter

front/src/Components/CadetPage/CadetFilter.js, front/src/Components/ProjectDetail/CheckModal.js, front/src/Components/ProjectDetail/MemberCard.js, front/src/Components/ProjectDetail/ProjectComment.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/Components/ProjectDetail/ProjectInfo.js, front/src/Components/ProjectDetail/ProjectStatus.js, front/src/Components/ProjectDetail/WaitList.js, front/src/SCSS/ProjectDetail/MemberList.scss, front/src/SCSS/ProjectDetail/ProjectDetail.scss, front/src/SCSS/ProjectDetail/ProjectInfo.scss
=> fix : fix bugs

front/src/SCSS/Common/Chat/ChatCard.scss, front/src/skills.json
=> chore: #704 add hosting skills

back/src/module/cadetqueue.ts
cadet list 에 6명 초과로 나오는 현상을 수정합니다
=> [back] feat: #349 cadet list

back/src/routes/auth/auth.service.ts
=> [back] feat: #732 level

front/src/SCSS/AllProjectPage/ProjectGrid.scss, front/src/SCSS/AllProjectPage/ProjectTypeBar.scss, front/src/SCSS/Common/Navbar/Navbar.scss, front/src/SCSS/MainPage/Cards.scss
- 프로젝트 목록 페이지 카드가 늘어나보이는 문제,
- 기타 모바일에서 반응형으로 수정하였습니다
=> feat: #760 add responsive project list

back/src/routes/project/project.service.ts
- 프로젝트의 상태가 변할 때, 해당 프로젝트 팀의 관심버튼을 누르고 팀의 멤버일 경우, 중복된 피드알림이 전송되는 오류를 수정했습니다.
- 팀장이 프로젝트의 상태를 임의로 변경할 때, 이전 상태와 변경할 상태가 같을 경우, 오류를 반환합니다.
=> fix: #658 fix overlap feed notification error

back/src/routes/project/project.controller.ts, back/src/routes/project/project.service.ts
- 조회수 증가 API인 updateViewCount API를 추가하고, 기존의 getContent API에서의 조회수 증가 로직을 제거하였습니다.
=> feat: #780 add updateViewCount API

front/src/Components/ProjectEditPage/Modal.js, front/src/SCSS/ProjectEditPage/Modal.scss
- 모달창이 띄워졌을 때 백그라운드 조작을 못하도록 전체 화면을 덮는 div를 추가해주었습니다.
=> feat: #787 modal background

back/src/interface/chat.interface.ts, back/src/models/chat/lastchat.mongo.ts, back/src/routes/chat/chat.controller.ts, back/src/routes/chat/chat.service.ts
=> [back] feat: #766 #797 chat change structure

front/src/Components/AllProjectPage/ProjectTypeBar.js, front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectDetail.js, front/src/Components/ProjectDetail/ProjectStatusChange.js, front/src/SCSS/AllProjectPage/ProjectTypeBar.scss, front/src/SCSS/CadetPage/CadetFilter.scss, front/src/SCSS/ProjectDetail/MemberList.scss
- 조회수 올려주는 기능을 프로젝트 데이터 가져오는 api에서 별도로 분리한
api로 적용함.
=> fix : viewcount fix

back/src/routes/project/project.service.ts
- 팀 멤버가 팀을 나가는 경우, 나간 멤버의 포지션을 모집포지션으로 추가합니다.
=> feat: #606 add recruiting position when member exit

back/src/routes/project/project.service.ts, front/src/Components/ProjectDetail/CheckModal.js
- 팀원의 포지션을 변경했을 때, 팀장의 포지션이 변경되는 오류를 수정하였습니다.
=> fix: #801 fix position change error

front/src/Components/ProjectDetail/MemberList.js, front/src/Components/ProjectDetail/ProjectInfo.js
- 포지션을 선택해서 지원할 때, 잘못된 포지션으로 적용되는 에러를 수정하였습니다.
- 모달 적용을 잘못하면서 에러가 발생하였습니다.
- 이외에도 프로젝트 나가기 버튼에도 모달을 적용했습니다.
=> fix : #849 fix selecting position error

back/src/interface/token.interface.ts, back/src/models/user/otoken.model.ts, back/src/models/user/user.model.ts, back/src/routes/auth/auth.controller.ts, back/src/routes/auth/auth.service.ts, back/src/routes/auth/oauth.ts, back/src/routes/auth/oauth/google.ts, back/src/routes/auth/oauth/intra.ts
구글 인증, 로그인 부분을 추가했습니다.
인트라 계정으로 로그인하여 구글 인증을 진행하면, 이후 구글 로그인을 사용할 수 있습니다.
구글 로그인 시 동일 계정으로 로그인 됩니다.
main에 merge 하면 프론트 엔드 완성까지 backend는 배포할 수 없습니다.
필요한 배포 작업이 있다면 먼저 진행해주시고, comment로 남겨주세요.
=> [back] feat: #852 #853 added google auth, refactoring

back/src/module/aws/s3.ts
=> [back] feat: #858 fixed image crash

back/src/interface/token.interface.ts, back/src/models/user/otoken.model.ts, back/src/models/user/user.model.ts, back/src/routes/auth/auth.controller.ts, back/src/routes/auth/auth.service.ts, back/src/routes/auth/oauth.ts, back/src/routes/auth/oauth/google.ts, back/src/routes/auth/oauth/intra.ts
프로필 이미지 이슈로 취소했던 머지를 다시 진행합니다.
=> feat: #852 #853 added google auth, refactoring

back/src/routes/auth/auth.service.ts, back/src/routes/auth/oauth/google.ts
redirection url 에 따라 환경변수를 분리해주었습니다.
연결이 안된다고 하셔서 바로 머지 하겠습니다.
=> [back] feat: split redirection url

back/src/routes/auth/auth.service.ts, back/src/routes/auth/oauth/intra.ts
=> [back] feat: split intra api

back/src/routes/user/user.service.ts
/user/me 에서 구글 이메일을 가져옵니다. 이메일이 없으면 null로 표기됩니다.
=> [back] feat: add API user/me to return gmail

back/src/routes/auth/auth.controller.ts, back/src/routes/auth/auth.service.ts, back/src/routes/auth/oauth/google.ts
=> [back] feat: merged intra sign up, sign in
